[project]
name = "filtergenie"
version = "0.1.0"
description = "FilterGenie: AI-powered filtering"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "duckdb>=1.2.2",
    "fastapi[standard]>=0.115.12",
    "openai>=1.73.0",
    "pillow>=11.1.0",
    "pydantic-settings>=2.8.1",
    "requests>=2.32.3",
    "structlog>=25.2.0",
]

[project.optional-dependencies]
local = [
    "accelerate>=1.6.0",
    "datasets>=3.5.0",
    "outlines>=0.2.3",
    "sentencepiece>=0.2.0",
    "transformers>=4.51.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["backend"]
