services:
  - type: web
    name: smartfilter-api
    plan: free

    # Source code information
    repo: https://github.com/daltunay/ecommerce-smart-filtering
    runtime: docker
    dockerfilePath: ./Dockerfile

    # Deployment configuration
    region: oregon
    autoDeploy: true
    healthCheckPath: /health

    # Environment variables
    envVars:
      - key: OPENAI_BASE_URL
        value: "https://generativelanguage.googleapis.com/v1beta/openai/"
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        generateValue: true
      - key: USE_LOCAL
        value: "false"
