services:
  - type: web
    name: filtergenie-api
    plan: free

    # Source code information
    repo: https://github.com/daltunay/filtergenie
    runtime: docker
    dockerfilePath: ./Dockerfile

    # Deployment configuration
    region: oregon
    autoDeploy: true
    healthCheckPath: /health

    # Environment variables
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: API_KEY
        generateValue: true
