name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Set up Playwright
        run: |
          uv run playwright install --with-deps firefox

      - name: Run tests
        run: |
          uv run pytest backend/tests -v

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() # Upload even if tests fail
        with:
          name: pytest-results
          path: |
            .pytest_cache
            pytest-report.xml
          retention-days: 7
